### PR TITLE
add support for BUCKET_NAME env variable for tuning halving benchmark

### PR DESCRIPTION
**Pull request by jingren1021**
Created a new pull request after accidentally closing the previous one.
Added env variable to the YAML files and docker-compose.yml files.
Changes are made referencing previous commit  #54 which added BUCKET_NAME env variable to video analytics.
Please review. 

Sorry for all the mess with pull requests.

### CODE REVIEW

**Comment by shyamjesal** [comment]
The PR looks good to me.
Can you please test it once. We can merge once the tests are successful.

**Comment by ustiugov** [comment]
@jingren1021 please check if the docker-compose test works in your local env and let us know, then one of us can test your setup as well.

**Comment by jingren1021** [comment]
I have tested it in my local environment and it worked fine.

**Comment by ustiugov** [comment]
thanks, @jingren1021 

@shyamjesal as you re-running things recently anyways, could you please test the docker-compose and knative setup and get back to us?

**Comment by ustiugov** [comment]
@shyamjesal any updates?

@jingren1021 we don't allow merge commits, could you use git or webUI rebase instead?

**Comment by jingren1021** [comment]
I have rebased to [ace2113](https://github.com/vhive-serverless/vSwarm/commit/ace2113bc0b15d285e61a20c4bdee067bf78722a).

**Review by shyamjesal — APPROVED** [review]

**Comment by shyamjesal** [comment]
Hi @jingren1021, sorry for the delay.
I have tested the code on a vhive cluster and it works. Please rebase and merge.

Thanks for the good work :)

**Comment by jingren1021** [comment]
I have resolved merge conflicts and rebased to [d6f1ee1](https://github.com/vhive-serverless/vSwarm/commit/d6f1ee181f0f2fd51bad9e899675f48dab7a0acd) (Lambda Invocation now through Python Script). Please review.

However, it seems to me that the vhiveease/tuning-halving-trainer and driver docker images on docker hub still uses old storage.py and tracing.py files and caused issue with newer driver/main.py trainer/main.py files. I will test the code on vhive cluster again after the docker images on docker hub have been updated.

**Comment by shyamjesal** [comment]
We have a pipeline to build and upload all images. I will update here once the images are up, then you can test.

**Comment by jingren1021** [comment]
I have signed-off this using $git commit --amend --signoff .

**Comment by jingren1021** [comment]
The docker images have been updated.

**Pull request merged**
