### PR TITLE
Bug Fixes and Issue Resolution in Stacking-Training

### PR DESCRIPTION
**Pull request by alannair**
This PR incorporates the following into the stacking-training benchmark.
- Applies Updated Knative Runners. Closes [#266](https://github.com/vhive-serverless/vSwarm/issues/266).
- In a [previous commit](https://github.com/vhive-serverless/vSwarm/commit/6663bec23dd21381ed6d3721e9a52e5d5726d307), the github workflow manifests had not been updated. This caused the _Test Docker Compose_ job to fail, as the environment variable `BUCKET_NAME` had not been configured, causing an empty string to be passed to the function (see [log](https://github.com/vhive-serverless/vSwarm/actions/runs/3533960680/jobs/5970282187)). This has also been fixed in this PR. 
  Note that `os.getenv('ENV_VAR', 'DEFAULT_VAL')` returns `DEFAULT_VAL` only if `ENV_VAR` is not set. This does not happen if `ENV_VAR` is set to an empty string, which occurs when `ENV_VAR` is created (in `docker-compose.yaml`) but not set to a value.
- Updated Readme, Placed repeated environment variables in the workflow at a single place, etc.

### CODE REVIEW

**Comment by alannair** [comment]
Hi @jingren1021. I am tagging you here since this PR may be of interest to you in your contributions to vSwarm.

**Comment by shyamjesal** [comment]
We used to use [envsubst](https://www.baeldung.com/linux/envsubst-command) to replace those environment variables in yaml files. 
The `kn_deploy.sh` script has a [line](https://github.com/vhive-serverless/vSwarm/blob/1aabd77bb11911909e4253918b357e9c7b16c4de/tools/kn_deploy.sh#L33) to do this. This is a hacky way to do things, but I believe this is quicker wrt creating a kubectl configmap.

**Comment by alannair** [comment]
@shyamjesal In the process of applying the updated knative runners, some changes were made because of which _kn_deploy.sh_ stops working as expected. 
The old (defunct) knative workflows ran on **stock-knative** while the new ones run on **ubuntu-20.04**. If we use _kn_deploy.sh_ then the new runner fails with the error `kn: command not found` (see [log](https://github.com/vhive-serverless/vSwarm/actions/runs/3599454165/jobs/6063159456#step:9:29)). This is because _kn_deploy.sh_ uses `kn service apply` to deploy the functions.

So, I went with `kubectl apply` on my workflows (including the [map-reduce workflow](https://github.com/vhive-serverless/vSwarm/blob/main/.github/workflows/e2e-map-reduce.yml) which is now on `main` branch). That is how I missed the _envsubst_ thing, and I looked for ways to work around the environment variable issue, finally settling on `kubectl secret` for sensitive data and `kubectl configmap` for other data.

So there are two possible solutions here.
1. The hacky way: Edit _kn_deploy.sh_ to use `kubectl apply` instead of `kn service apply` (and rename the file to _kubectl_apply.sh_ or something), and use this file for function deployment on all benchmarks. This is _hacky_ because it uses _envsubst_ to substitute pass parameters via environment variables.
2. The (in my opinion) proper way: Instead of environment variables, use `kubectl secret` for sensitive data and `kubectl configmap` for other data. Apply this to all benchmarks in the process of updating the knative runners, and then decommission _kn_deploy.sh_ (do we really need a separate bash file for just a one-line command?)

@dhschall @ustiugov  Please weigh in here. Knative runners shall be applied to the remaining benchmarks as per what we decide here.

For comparison, see [old knative runner](https://github.com/vhive-serverless/vSwarm/blob/main/.github/workflows/e2e-video-analytics.yml) example and [new knative runner](https://github.com/vhive-serverless/vSwarm/blob/main/.github/workflows/e2e-map-reduce.yml) example.

**Comment by alannair** [comment]
Update:
We shall be sticking with `kn` and using environment variables to set the values rather than `kubectl secrets` or `configmap`. The PR description and code have been updated. The same convention shall be followed for updating knative runners to the remaining benchmarks.

**Review by shyamjesal — APPROVED** [review]

**Pull request merged**
