### PR TITLE
Update Maintainers list

### LINKED ISSUE #399: Update Maintainers list
**Describe the enhancement**
We need to update the following in the maintainers list:
- @ustiugov website link breaks -> change to https://ustiugov.github.io/
- Shift responsibility from him to others.
- We should note somewhere that questions regarding multi cloud should include @alannair 

Full apps:
| Benchmark                     | Maintainer | 
| ----------------------------- | ------------- | 
| Chained Function Eventing     | 
| Chained Function Serving      | 
| Map-Reduce                    | 
| Corral (word count)           | 
| Stacking-Training             |
| Hyperparameter Tuning Halving | 
| Video Analytics               | 
| Distributed compilation (gg)  | 
| Video decoding (gg)           
| Fibonacci (gg)                |

Standalone:
| Benchmark                     | Maintainer | 
| ----------------------------- | ------------- | 
| 25x functions | @dhschall  |

Multi cloud containers (lambda)
@alannair

### PR DESCRIPTION
**Pull request by dhschall**
closes #399 

Full apps:
| Benchmark                     | Maintainer | 
| ----------------------------- | ------------- | 
| Chained Function Eventing     | 
| Chained Function Serving      | 
| Map-Reduce                    | 
| Corral (word count)           | 
| Stacking-Training             |
| Hyperparameter Tuning Halving | 
| Video Analytics               | 
| Distributed compilation (gg)  | 
| Video decoding (gg)           
| Fibonacci (gg)                |

Standalone:
| Benchmark                     | Maintainer | 
| ----------------------------- | ------------- | 
| 25x functions | @dhschall  |

Multi cloud containers (lambda)
@alannair

### CODE REVIEW

**Comment by dhschall** [comment]
Hey @ustiugov , @alannair and @shyamjesal 
I think we should update the maintainers list and shift some responsibilities.
I am not sure who is maintaining the full application functions.
Can you maybe modify or make suggestions?

**Comment by alannair** [comment]
I'm confident about `map-reduce`, `stacking-training`, `tuning-halving`, `aes`, `auth` and `fibonacci`. You may assign me to any subset of these benchmarks. 
Multi-Cloud support as well.

**Comment by ustiugov** [comment]
@dhschall I suggest to divide the effort among @shyamjesal and @alannair. I don't have capacity to maintain any benchmarks anymore, unfortunately.

**Comment by shyamjesal** [comment]
I can manage gg ones, chained serving and video analytics.

**Comment by ustiugov** [comment]
thank you, everyone. 

@dhschall, can you please update the list accordingly? you can list me for Corral.

**Pull request merged**
