### PR TITLE
AWS Lambda Support for Map-Reduce

### PR DESCRIPTION
**Pull request by alannair**
+ Removed some unused modules
+ Does not support tracing for Lambda yet

### CODE REVIEW

**Review by ustiugov — CHANGES_REQUESTED** [review]
There is a lot of code duplication, this wouldn't work. You need to re-structure the code minimizing code duplicates. Only the "gRPC handler" and `lambda_handler` should be different but the functionality they use should be the same. It's clear that having a single class doesn't make sense, so need to find a better solution. Can you talk to @shyamjesal, he has more experience in OOP with python.

However, I do agree with the way you splitted module imports. Also, what I would suggest is to split each main.py into multi-cloud wrapper "main.py" and cloud-agnostic "map.py/reduce.py" that contain the share code.

**Comment by alannair** [comment]
@ustiugov Please review this current commit.
I have separated the functional and non-functional parts into different files as you suggested, and have used a separate class as a wrapper for each cloud platform (in main.py). There is not much code duplication now, in my opinion.

**Review by ustiugov — CHANGES_REQUESTED** [review]
looks better, thank you. 

- [x] please make sure there is no duplicate code for get/put methods. e.g., make a separate object/structure with a client and the methods and include it as a field in the "servicer" objects
- [ ] need to find a way to automatically test both implementations. How do you test it? e.g., need to compare the output files with the reference output. Regarding testing of the Knative implementation, you can discuss it with @dhschall. for AWS Lambda, need to deploy these containers in AWS in a workflow.

**Comment by alannair** [comment]
Pull Request has been shited to [#298](https://github.com/vhive-serverless/vSwarm/pull/298).
The source fork has been deleted and all the code was moved to a new branch on this repository itself (see [#297](https://github.com/vhive-serverless/vSwarm/pull/297))

**Pull request closed without merging**
